-- BitBuilders Hackathon: Smart Invoicing System
-- SQL Schema for Supabase

-- This script creates the necessary tables, enables Row Level Security (RLS),
-- and sets up basic policies for a public-facing application.
-- Run this script in your Supabase project's SQL Editor.

-- 1. Table for Categories and their associated tax rates
-- Admins will manage this table.
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  tax_rate REAL NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table for Invoices
-- A new record is created here every time a cashier completes a checkout.
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  total_amount REAL NOT NULL,
  total_tax REAL NOT NULL
);

-- 3. Table for individual items within an invoice
-- Connects items to a specific invoice.
CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE NOT NULL,
  item_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  price_per_item REAL NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  tax REAL NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 4. Set up Row Level Security (RLS)
-- This is a security best practice for Supabase.
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies
-- These policies determine who can access or modify the data.
-- For this hackathon, we'll allow public read and write access,
-- as there is no authentication.

-- Policies for 'categories' table
DROP POLICY IF EXISTS "Allow public read access" ON categories;
CREATE POLICY "Allow public read access" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous insert access" ON categories;
CREATE POLICY "Allow anonymous insert access" ON categories FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anonymous delete access" ON categories;
CREATE POLICY "Allow anonymous delete access" ON categories FOR DELETE USING (true);


-- Policies for 'invoices' table
DROP POLICY IF EXISTS "Allow public read access" ON invoices;
CREATE POLICY "Allow public read access" ON invoices FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous insert access" ON invoices;
CREATE POLICY "Allow anonymous insert access" ON invoices FOR INSERT WITH CHECK (true);


-- Policies for 'invoice_items' table
DROP POLICY IF EXISTS "Allow public read access" ON invoice_items;
CREATE POLICY "Allow public read access" ON invoice_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow anonymous insert access" ON invoice_items;
CREATE POLICY "Allow anonymous insert access" ON invoice_items FOR INSERT WITH CHECK (true);
